/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type trMessage from '../locales/tr/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof trMessage;

export type DevLocale = 'en' | 'tr';
